In [2]:
import pandas as pd
import numpy as np

In [100]:
data = pd.read_csv('/Users/triciascy/code/toothyachy/yumspeak/final_df.csv').drop(columns='Unnamed: 0')
data.head()

,Restaurant Name,Address
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln
1,(Viet Taste) Vietnamese Cuisine @ Food Junctio...,"1 Kim Seng Promenade, Floor 3"
2,01-22 Wufu Hakka Noodle,Singapore
3,116 PH·ªê ƒê√äM,116 Mackenzie Rd
4,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, #01-45, 49-51 icon village"

In [101]:
#get lat lng using mapbox
import geocoder

def get_latlng(address):
    g = geocoder.mapbox(f"{address},SG", key='pk.eyJ1Ijoic2N5dHJpY2lhIiwiYSI6ImNtMGM3c3h3cDAwYTcya3ExeTB1cWd4MzMifQ.QWP6BN8Me5GDTisQV5Rcaw')
    latlng = (g.json['lat'], g.json['lng'])

    return np.array(latlng)

In [102]:
# get coordinates for address
def coordinates(address):
    if address == 'Singapore':
        return np.array((1.288799, 103.840943))
    else:
        return get_latlng(address)

In [103]:
df = data.copy()
df

,Restaurant Name,Address
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln
1,(Viet Taste) Vietnamese Cuisine @ Food Junctio...,"1 Kim Seng Promenade, Floor 3"
2,01-22 Wufu Hakka Noodle,Singapore
3,116 PH·ªê ƒê√äM,116 Mackenzie Rd
4,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, #01-45, 49-51 icon village"
...,...,...
3275,È∫ªËæ£ËØ±ÊÉë Spice Spirits Singapore,14 Foch Rd
3276,ÈºéÈºéÁ¥ÖÈ∫ªËæ£È¶ôÈçã Ding Ding Hong Mala HotPot,"1 Kadayanallur St, #01-41"
3277,ÏïàÎÖïÌïòÏÑ∏Ïöî Hello Korean BBQ,45 / 46 Circular Rd
3278,ÏòàÏïΩ YeYak Korean Restaurant,Singapore
3279,ùóîùó™ùóîùóóùóõ | Royal Indian Dining & Lounge,"01-33H, The Centrepoint, 176 Orchard Rd"

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3280 entries, 0 to 3279
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Restaurant Name  3280 non-null   object
 1   Address          3280 non-null   object
dtypes: object(2)
memory usage: 51.4+ KB

In [104]:
df['Address'] = df['Address'].replace({'#*': ''}, regex=True)
df

,Restaurant Name,Address
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln
1,(Viet Taste) Vietnamese Cuisine @ Food Junctio...,"1 Kim Seng Promenade, Floor 3"
2,01-22 Wufu Hakka Noodle,Singapore
3,116 PH·ªê ƒê√äM,116 Mackenzie Rd
4,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, 01-45, 49-51 icon village"
...,...,...
3275,È∫ªËæ£ËØ±ÊÉë Spice Spirits Singapore,14 Foch Rd
3276,ÈºéÈºéÁ¥ÖÈ∫ªËæ£È¶ôÈçã Ding Ding Hong Mala HotPot,"1 Kadayanallur St, 01-41"
3277,ÏïàÎÖïÌïòÏÑ∏Ïöî Hello Korean BBQ,45 / 46 Circular Rd
3278,ÏòàÏïΩ YeYak Korean Restaurant,Singapore
3279,ùóîùó™ùóîùóóùóõ | Royal Indian Dining & Lounge,"01-33H, The Centrepoint, 176 Orchard Rd"

In [105]:
df.to_csv('/Users/triciascy/code/toothyachy/yumspeak/final_df.csv')

In [107]:
df_0_100 = df.iloc[0:100]
df_0_100

,Restaurant Name,Address
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln
1,(Viet Taste) Vietnamese Cuisine @ Food Junctio...,"1 Kim Seng Promenade, Floor 3"
2,01-22 Wufu Hakka Noodle,Singapore
3,116 PH·ªê ƒê√äM,116 Mackenzie Rd
4,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, 01-45, 49-51 icon village"
...,...,...
95,Ah Pang Steamboat Seafood,"159 Mei Ling St, 02-21 Food Center"
96,Ah Ter Teochew Fishball Noodles,"7 Maxwell Rd, 01-14"
97,Ah Yat Seafood Restaurant,"401 Havelock Rd, 03-00 Hotel Miramar"
98,Ah Yat Seafood Restaurant,19 Sims Way
99,Ai Cafe Singapore - Best Cafe Singapore,74 Horne Rd

In [108]:
df_0_100['coordinates'] = df_0_100['Address'].apply(coordinates)
df_0_100

/var/folders/hr/cpz20c0528n3lthhycz7r5ch0000gn/T/ipykernel_8817/442528455.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_0_100['coordinates'] = df_0_100['Address'].apply(coordinates)

,Restaurant Name,Address,coordinates
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln,"[1.381223, 103.752383]"
1,(Viet Taste) Vietnamese Cuisine @ Food Junctio...,"1 Kim Seng Promenade, Floor 3","[1.293613, 103.832008]"
2,01-22 Wufu Hakka Noodle,Singapore,"[1.288799, 103.840943]"
3,116 PH·ªê ƒê√äM,116 Mackenzie Rd,"[1.306633, 103.84725]"
4,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, 01-45, 49-51 icon village","[47.222607, -65.15526]"
...,...,...,...
95,Ah Pang Steamboat Seafood,"159 Mei Ling St, 02-21 Food Center","[1.351616, 103.808053]"
96,Ah Ter Teochew Fishball Noodles,"7 Maxwell Rd, 01-14","[1.279661, 103.844721]"
97,Ah Yat Seafood Restaurant,"401 Havelock Rd, 03-00 Hotel Miramar","[1.351616, 103.808053]"
98,Ah Yat Seafood Restaurant,19 Sims Way,"[1.312144, 103.874681]"
99,Ai Cafe Singapore - Best Cafe Singapore,74 Horne Rd,"[1.310651, 103.860875]"

In [117]:
df_0_100['lat'] = df_0_100['coordinates'].apply(lambda x: x[0])
df_0_100

/var/folders/hr/cpz20c0528n3lthhycz7r5ch0000gn/T/ipykernel_8817/3659174689.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_0_100['lat'] = df_0_100['coordinates'].apply(lambda x: x[0])

,Restaurant Name,Address,coordinates,lat
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln,"[1.381223, 103.752383]",1.381223
1,(Viet Taste) Vietnamese Cuisine @ Food Junctio...,"1 Kim Seng Promenade, Floor 3","[1.293613, 103.832008]",1.293613
2,01-22 Wufu Hakka Noodle,Singapore,"[1.288799, 103.840943]",1.288799
3,116 PH·ªê ƒê√äM,116 Mackenzie Rd,"[1.306633, 103.84725]",1.306633
4,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, 01-45, 49-51 icon village","[47.222607, -65.15526]",47.222607
...,...,...,...,...
95,Ah Pang Steamboat Seafood,"159 Mei Ling St, 02-21 Food Center","[1.351616, 103.808053]",1.351616
96,Ah Ter Teochew Fishball Noodles,"7 Maxwell Rd, 01-14","[1.279661, 103.844721]",1.279661
97,Ah Yat Seafood Restaurant,"401 Havelock Rd, 03-00 Hotel Miramar","[1.351616, 103.808053]",1.351616
98,Ah Yat Seafood Restaurant,19 Sims Way,"[1.312144, 103.874681]",1.312144
99,Ai Cafe Singapore - Best Cafe Singapore,74 Horne Rd,"[1.310651, 103.860875]",1.310651

In [88]:
df_0_100['lng'] = df_0_100['coordinates'].apply(lambda x: x[1])
df_0_100

/var/folders/hr/cpz20c0528n3lthhycz7r5ch0000gn/T/ipykernel_8817/2281791015.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_0_100['lng'] = df_0_100['coordinates'].apply(lambda x: x[1])

,Restaurant Name,Address,coordinates,lat,lng
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln,"[1.381223, 103.752383]",1.381223,103.752383
1,(Viet Taste) Vietnamese Cuisine @ Food Junctio...,"1 Kim Seng Promenade, Floor 3","[1.293613, 103.832008]",1.293613,103.832008
2,01-22 Wufu Hakka Noodle,Singapore,"[1.288799, 103.840943]",1.288799,103.840943
3,116 PH·ªê ƒê√äM,116 Mackenzie Rd,"[1.306633, 103.84725]",1.306633,103.847250
4,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, 01-45, 49-51 icon village","[47.222607, -65.15526]",47.222607,-65.155260
...,...,...,...,...,...
95,Ah Pang Steamboat Seafood,"159 Mei Ling St, 02-21 Food Center","[1.351616, 103.808053]",1.351616,103.808053
96,Ah Ter Teochew Fishball Noodles,"7 Maxwell Rd, 01-14","[1.279661, 103.844721]",1.279661,103.844721
97,Ah Yat Seafood Restaurant,"401 Havelock Rd, 03-00 Hotel Miramar","[1.351616, 103.808053]",1.351616,103.808053
98,Ah Yat Seafood Restaurant,19 Sims Way,"[1.312144, 103.874681]",1.312144,103.874681
99,Ai Cafe Singapore - Best Cafe Singapore,74 Horne Rd,"[1.310651, 103.860875]",1.310651,103.860875

In [89]:
df_0_100 = df_0_100.drop(columns='coordinates')
df_0_100

,Restaurant Name,Address,lat,lng
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln,1.381223,103.752383
1,(Viet Taste) Vietnamese Cuisine @ Food Junctio...,"1 Kim Seng Promenade, Floor 3",1.293613,103.832008
2,01-22 Wufu Hakka Noodle,Singapore,1.288799,103.840943
3,116 PH·ªê ƒê√äM,116 Mackenzie Rd,1.306633,103.847250
4,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, 01-45, 49-51 icon village",47.222607,-65.155260
...,...,...,...,...
95,Ah Pang Steamboat Seafood,"159 Mei Ling St, 02-21 Food Center",1.351616,103.808053
96,Ah Ter Teochew Fishball Noodles,"7 Maxwell Rd, 01-14",1.279661,103.844721
97,Ah Yat Seafood Restaurant,"401 Havelock Rd, 03-00 Hotel Miramar",1.351616,103.808053
98,Ah Yat Seafood Restaurant,19 Sims Way,1.312144,103.874681
99,Ai Cafe Singapore - Best Cafe Singapore,74 Horne Rd,1.310651,103.860875

In [90]:
df_0_100.to_csv('/Users/triciascy/code/toothyachy/yumspeak/df_0_100.csv')

In [151]:
def lat_lng(df):
    df['Address'] = df['Address'].replace({'#*': ''}, regex=True)
    df['coordinates'] = df['Address'].apply(coordinates)
    df['lat'] = df['coordinates'].apply(lambda x: x[0])
    df['lng'] = df['coordinates'].apply(lambda x: x[1])
    df = df.drop(columns='coordinates')
    return df

In [157]:
final_df = pd.read_csv('/Users/triciascy/code/toothyachy/yumspeak/master_restaurant_df.csv').drop(columns='Unnamed: 0')
final_df

,Restaurant Name,Address
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln
1,01-22 Wufu Hakka Noodle,Singapore
2,116 PH·ªê ƒê√äM,116 Mackenzie Rd
3,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, #01-45, 49-51 icon village, Sing..."
4,123 Z√¥ The Vi·ªát Kitchen,"18 Raffles Quay, 01-48 Lau Pa Sat"
...,...,...
3190,È∫ªËæ£ËØ±ÊÉë Spice Spirits Singapore,14 Foch Rd
3191,ÈºéÈºéÁ¥ÖÈ∫ªËæ£È¶ôÈçã Ding Ding Hong Mala HotPot,"1 Kadayanallur St, 01-41"
3192,ÏïàÎÖïÌïòÏÑ∏Ïöî Hello Korean BBQ,45 / 46 Circular Rd
3193,ÏòàÏïΩ YeYak Korean Restaurant,Singapore
3194,ùóîùó™ùóîùóóùóõ | Royal Indian Dining & Lounge,"01-33H, The Centrepoint, 176 Orchard Rd"

In [158]:
df_300 = final_df.iloc[0:300].copy()
df_300

,Restaurant Name,Address
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln
1,01-22 Wufu Hakka Noodle,Singapore
2,116 PH·ªê ƒê√äM,116 Mackenzie Rd
3,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, #01-45, 49-51 icon village, Sing..."
4,123 Z√¥ The Vi·ªát Kitchen,"18 Raffles Quay, 01-48 Lau Pa Sat"
...,...,...
295,Binomio,"20 Craig Rd, 01-02 Craig Place"
296,Birds of Paradise Gelato Boutique (Craig),"53 Craig Rd, 01-01"
297,Birds of a Feather,"115 Amoy St, 01-01"
298,Bistecca Tuscan Steakhouse,26 Mohamed Sultan Rd
299,Bistro @ SICC,"180 Island Club Rd, Lobby Level The Singapore ..."

In [154]:
df_0_300 = lat_lng(df_300)
df_0_300

,Restaurant Name,Address,lat,lng
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln,1.381223,103.752383
1,01-22 Wufu Hakka Noodle,Singapore,1.288799,103.840943
2,116 PH·ªê ƒê√äM,116 Mackenzie Rd,1.306633,103.847250
3,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, 01-45, 49-51 icon village, Singa...",1.275493,103.844649
4,123 Z√¥ The Vi·ªát Kitchen,"18 Raffles Quay, 01-48 Lau Pa Sat",41.091140,-78.290746
...,...,...,...,...
295,Binomio,"20 Craig Rd, 01-02 Craig Place",-31.371689,-62.099266
296,Birds of Paradise Gelato Boutique (Craig),"53 Craig Rd, 01-01",1.277643,103.842496
297,Birds of a Feather,"115 Amoy St, 01-01",1.283020,103.848357
298,Bistecca Tuscan Steakhouse,26 Mohamed Sultan Rd,1.293431,103.841181
299,Bistro @ SICC,"180 Island Club Rd, Lobby Level The Singapore ...",39.832440,-94.821976

In [155]:
df_0_300.to_csv('/Users/triciascy/code/toothyachy/yumspeak/df_0_300.csv')

In [161]:
df_600 = final_df.iloc[300:600].copy()
df_300_600 = lat_lng(df_600)
df_300_600

,Restaurant Name,Address,lat,lng
300,Bistro Aseana Pasta & Skewer Bar,Singapore,1.288799,103.840943
301,Bistro Du Vin,Singapore,1.288799,103.840943
302,Bistro Eminami Halal Vietnam,46 Kandahar St,1.301823,103.859916
303,Bistro Etroit Ep.2,Singapore,1.288799,103.840943
304,Black Cow,"26 Beach Rd, B1-20 South Beach Avenue",44.612892,-124.050310
...,...,...,...,...
595,D9 Cakery,"581 Orchard Rd, Level 1 voco Orchard Singapore",1.351616,103.808053
596,DANIU TEOCHEW SEAFOOD RESTAURANT,61 Kampong Bahru Rd,1.276544,103.835976
597,DAWN,78 South Bridge Rd,1.286831,103.847816
598,DESEM - Republic Plaza,"9 Raffles Pl, B1 - 16 Republic plaza",53.646305,18.729645
599,DPELANGI,"LEVEL 6 NOVOTEL HOTEL, 177A RIVER VALLEY ROAD ...",45.219837,-67.260390

In [163]:
df_300_600.to_csv('/Users/triciascy/code/toothyachy/yumspeak/df_300_600.csv')

In [178]:
df = final_df.copy()
df_all = lat_lng(df)
df_all

,Restaurant Name,Address,lat,lng
0,(Fu Chan) Harummanis Muslim Food,145 Teck Whye Ln,1.381223,103.752383
1,01-22 Wufu Hakka Noodle,Singapore,1.288799,103.840943
2,116 PH·ªê ƒê√äM,116 Mackenzie Rd,1.306633,103.847250
3,123 Z√î - ·∫®m Th·ª±c Vi·ªát,"12 Gopeng St, 01-45, 49-51 icon village, Singa...",1.275493,103.844649
4,123 Z√¥ The Vi·ªát Kitchen,"18 Raffles Quay, 01-48 Lau Pa Sat",41.091140,-78.290746
...,...,...,...,...
3190,È∫ªËæ£ËØ±ÊÉë Spice Spirits Singapore,14 Foch Rd,1.311998,103.859903
3191,ÈºéÈºéÁ¥ÖÈ∫ªËæ£È¶ôÈçã Ding Ding Hong Mala HotPot,"1 Kadayanallur St, 01-41",1.280374,103.844659
3192,ÏïàÎÖïÌïòÏÑ∏Ïöî Hello Korean BBQ,45 / 46 Circular Rd,1.286116,103.849490
3193,ÏòàÏïΩ YeYak Korean Restaurant,Singapore,1.288799,103.840943
3194,ùóîùó™ùóîùóóùóõ | Royal Indian Dining & Lounge,"01-33H, The Centrepoint, 176 Orchard Rd",1.351616,103.808053

In [179]:
df_all.to_csv('/Users/triciascy/code/toothyachy/yumspeak/name_data/master_restaurant_df.csv') #index=False

In [168]:
df_600_900 = df_all.iloc[600:900].copy()
df_600_900.to_csv('/Users/triciascy/code/toothyachy/yumspeak/name_data/df_600_900.csv')

In [169]:
df_900_1200 = df_all.iloc[900:1200].copy()
df_900_1200.to_csv('/Users/triciascy/code/toothyachy/yumspeak/name_data/df_900_1200.csv')

In [170]:
df_1200_1500 = df_all.iloc[1200:1500].copy()
df_1200_1500.to_csv('/Users/triciascy/code/toothyachy/yumspeak/name_data/df_1200_1500.csv')

In [171]:
df_1500_1800 = df_all.iloc[1500:1800].copy()
df_1500_1800.to_csv('/Users/triciascy/code/toothyachy/yumspeak/name_data/df_1500_1800.csv')

In [172]:
df_1800_2100 = df_all.iloc[1800:2100].copy()
df_1800_2100.to_csv('/Users/triciascy/code/toothyachy/yumspeak/name_data/df_1800_2100.csv')

In [173]:
df_2100_2400 = df_all.iloc[2100:2400].copy()
df_2100_2400.to_csv('/Users/triciascy/code/toothyachy/yumspeak/name_data/df_2100_2400.csv')

In [174]:
df_2400_2700 = df_all.iloc[2400:2700].copy()
df_2400_2700.to_csv('/Users/triciascy/code/toothyachy/yumspeak/name_data/df_2400_2700.csv')

In [175]:
df_2700_3000 = df_all.iloc[2700:3000].copy()
df_2700_3000.to_csv('/Users/triciascy/code/toothyachy/yumspeak/name_data/df_2700_3000.csv')

In [177]:
df_3000_3194 = df_all.iloc[3000:].copy()
df_3000_3194.to_csv('/Users/triciascy/code/toothyachy/yumspeak/name_data/df_3000_3194.csv')